// Language translations
        const translations = {
            hu: {
                nav_home: 'Főoldal',
                nav_rooms: 'Szobák',
                nav_amenities: 'Szolgáltatások',
                nav_location: 'Helyszín',
                nav_gallery: 'Galéria',
                nav_booking: 'Kapcsolat',
                hero_subtitle: 'Hangulatos 3 hálószobás apartman Kőszegen',
                hero_cta: 'Foglaljon most',
                about_title: 'Üdvözöljük az Ön tökéletes kirándulásán',
                about_intro: 'Az Ön tökéletes kirándulása Kőszeg bájos középkori városában',
                about_description: 'Tapasztalja meg a kényelmet gyönyörű 3 hálószobás apartmanunkban, amely 5 ágyas és lenyűgöző kertre néző kilátással rendelkezik. Kőszeg szívében található ingatlanunk a modern kényelem és a történelmi varázs tökéletes keverékét kínálja.',
                highlight1_title: 'Tágas szállás',
                highlight1_desc: '3 hálószoba 5 kényelmes ággyal - tökéletes családok és csoportok számára',
                highlight2_title: 'Kiváló elhelyezkedés',
                highlight2_desc: 'A történelmi Kőszeg szívében, sétatávolságra minden látványosságtól',
                highlight3_title: 'Kert & Terasz',
                highlight3_desc: 'Pihenjen gyönyörű kertünkben terasz hozzáféréssel',
                rooms_title: 'Apartmanunk',
                room_name: '3 hálószobás apartman kertre néző kilátással',
                room_sleeping: 'Alvási lehetőségek',
                room_bed1: '1 franciaágy',
                room_bed2: '3 egyágyas',
                room_capacity: 'Legfeljebb 5 vendég részére',
                room_features_title: 'Szoba jellemzők',
                room_feat1: 'Lapos képernyős TV kábel csatornákkal',
                room_feat2: 'Légkondicionálás',
                room_feat3: 'Ingyenes WiFi',
                room_feat4: 'Kertre néző nézet',
                room_feat5: 'Terasz hozzáférés',
                amenities_title: 'Szolgáltatások',
                amenity_0: 'Teljesen felszerelt konyha',
                amenity_1: 'Mosogatógép',
                amenity_2: 'Sütő',
                amenity_3: 'Mikrohullámú sütő',
                amenity_4: 'Kenyérpirító',
                amenity_5: 'Kávéfőző',
                amenity_6: 'Lapos képernyős TV',
                amenity_7: 'Kábel csatornák',
                amenity_8: 'Ingyenes WiFi',
                amenity_9: 'Ingyenes parkolás',
                amenity_10: 'Légkondicionálás',
                amenity_11: 'Kert és terasz',
                amenity_12: 'Kandalló',
                amenity_13: 'Elektromos autó töltőállomás',
                amenity_14: 'Kedvencbarát',
                amenity_15: '24/7 Bejelentkezés',
                amenity_16: 'Kertre néző nézet',
                amenity_17: 'Vasaló és vasalódeszka',
                location_title: 'Helyszín és közeli látnivalók',
                location_intro: 'Fedezze fel Kőszeg középkori bájait és az osztrák-magyar határvidék szépségeit',
                attractions_title: 'Közeli látnivalók',
                attr_0: 'Jurisics Vár',
                attr_1: 'Kőszeg történelmi belváros',
                attr_2: 'Írottkő természetvédelmi terület',
                attr_3: 'Hétforrás',
                attr_4: 'Burg Lockenhaus (12 km)',
                attr_5: 'Sóferi tó (18 km)',
                gallery_title: 'Fotógaléria',
                booking_title: 'Foglaljon szállást',
                form_checkin: 'Érkezés dátuma',
                form_checkout: 'Távozás dátuma',
                form_adults: 'Felnőttek száma',
                form_children: 'Gyermekek száma',
                form_select: 'Válasszon...',
                form_submit: 'Elérhetőség ellenőrzése',
                checkin_title: 'Bejelentkezés és kijelentkezés időpontjai',
                checkin_label: 'Bejelentkezés:',
                checkout_label: 'Kijelentkezés:',
                footer_contact: 'Kapcsolattartási információk',
                footer_links: 'Gyors linkek',
                footer_copyright: '© 2025 Tessa Central House. Minden jog fenntartva.'
            },
            en: {
                nav_home: 'Home',
                nav_rooms: 'Rooms',
                nav_amenities: 'Amenities',
                nav_location: 'Location',
                nav_gallery: 'Gallery',
                nav_booking: 'Contact',
                hero_subtitle: 'Cozy 3-Bedroom Apartment in Kőszeg, Hungary',
                hero_cta: 'Book Your Stay',
                about_title: 'Welcome to Your Perfect Getaway',
                about_intro: 'Your perfect getaway in the charming medieval town of Kőszeg',
                about_description: 'Experience the comfort of our beautiful 3-bedroom apartment featuring 5 beds with stunning garden views. Located in the heart of Kőszeg, our property offers the perfect blend of modern amenities and historic charm.',
                highlight1_title: 'Spacious Accommodation',
                highlight1_desc: '3 bedrooms with 5 comfortable beds - perfect for families and groups',
                highlight2_title: 'Prime Location',
                highlight2_desc: 'In the heart of historic Kőszeg, walking distance to all attractions',
                highlight3_title: 'Garden Views & Terrace',
                highlight3_desc: 'Relax in our beautiful garden with outdoor terrace access',
                rooms_title: 'Our Apartment',
                room_name: '3-Bedroom Apartment with Garden View',
                room_sleeping: 'Sleeping Arrangements',
                room_bed1: '1 Double Bed',
                room_bed2: '3 Single Beds',
                room_capacity: 'Sleeps up to 5 guests',
                room_features_title: 'Room Features',
                room_feat1: 'Flat-screen TV with cable channels',
                room_feat2: 'Air conditioning',
                room_feat3: 'Free WiFi',
                room_feat4: 'Garden view',
                room_feat5: 'Terrace access',
                amenities_title: 'Amenities & Services',
                amenity_0: 'Fully Equipped Kitchen',
                amenity_1: 'Dishwasher',
                amenity_2: 'Oven',
                amenity_3: 'Microwave',
                amenity_4: 'Toaster',
                amenity_5: 'Coffee Maker',
                amenity_6: 'Flat-screen TV',
                amenity_7: 'Cable Channels',
                amenity_8: 'Free WiFi',
                amenity_9: 'Free Parking',
                amenity_10: 'Air Conditioning',
                amenity_11: 'Garden & Terrace',
                amenity_12: 'Fireplace',
                amenity_13: 'EV Charging Station',
                amenity_14: 'Pet Friendly',
                amenity_15: '24/7 Check-in',
                amenity_16: 'Garden View',
                amenity_17: 'Iron & Ironing Board',
                location_title: 'Location & Nearby Attractions',
                location_intro: 'Discover the medieval charm of Kőszeg and explore the beautiful Austrian-Hungarian border region',
                attractions_title: 'Nearby Attractions',
                attr_0: 'Jurisics Castle',
                attr_1: 'Kőszeg Town Center',
                attr_2: 'Írottkő Nature Park',
                attr_3: 'Seven Springs (Hétforrás)',
                attr_4: 'Burg Lockenhaus (12 km)',
                attr_5: 'Lake Sofer (18 km)',
                gallery_title: 'Photo Gallery',
                booking_title: 'Book Your Stay',
                form_checkin: 'Check-in Date',
                form_checkout: 'Check-out Date',
                form_adults: 'Number of Adults',
                form_children: 'Number of Children',
                form_select: 'Select...',
                form_submit: 'Check Availability',
                checkin_title: 'Check-in & Check-out Times',
                checkin_label: 'Check-in:',
                checkout_label: 'Check-out:',
                footer_contact: 'Contact Information',
                footer_links: 'Quick Links',
                footer_copyright: '© 2025 Tessa Central House. All rights reserved.'
            },
            de: {
                nav_home: 'Startseite',
                nav_rooms: 'Zimmer',
                nav_amenities: 'Ausstattung',
                nav_location: 'Standort',
                nav_gallery: 'Galerie',
                nav_booking: 'Kontakt',
                hero_subtitle: 'Gemütliche 3-Zimmer-Wohnung in Kőszeg, Ungarn',
                hero_cta: 'Jetzt buchen',
                about_title: 'Willkommen zu Ihrem perfekten Urlaub',
                about_intro: 'Ihr perfekter Urlaub in der charmanten mittelalterlichen Stadt Kőszeg',
                about_description: 'Erleben Sie den Komfort unserer schönen 3-Zimmer-Wohnung mit 5 Betten und herrlichem Gartenblick. Im Herzen von Kőszeg gelegen, bietet unser Anwesen die perfekte Mischung aus modernen Annehmlichkeiten und historischem Charme.',
                highlight1_title: 'Geräumige Unterkunft',
                highlight1_desc: '3 Schlafzimmer mit 5 bequemen Betten - perfekt für Familien und Gruppen',
                highlight2_title: 'Erstklassige Lage',
                highlight2_desc: 'Im Herzen des historischen Kőszeg, zu Fuß zu allen Sehenswürdigkeiten',
                highlight3_title: 'Garten & Terrasse',
                highlight3_desc: 'Entspannen Sie sich in unserem schönen Garten mit Terrassenzugang',
                rooms_title: 'Unsere Wohnung',
                room_name: '3-Zimmer-Wohnung mit Gartenblick',
                room_sleeping: 'Schlafmöglichkeiten',
                room_bed1: '1 Doppelbett',
                room_bed2: '3 Einzelbetten',
                room_capacity: 'Platz für bis zu 5 Gäste',
                room_features_title: 'Zimmerausstattung',
                room_feat1: 'Flachbildfernseher mit Kabelkanälen',
                room_feat2: 'Klimaanlage',
                room_feat3: 'Kostenfreies WLAN',
                room_feat4: 'Gartenblick',
                room_feat5: 'Terrassenzugang',
                amenities_title: 'Ausstattung & Services',
                amenity_0: 'Vollständig ausgestattete Küche',
                amenity_1: 'Geschirrspüler',
                amenity_2: 'Ofen',
                amenity_3: 'Mikrowelle',
                amenity_4: 'Toaster',
                amenity_5: 'Kaffeemaschine',
                amenity_6: 'Flachbildfernseher',
                amenity_7: 'Kabelkanäle',
                amenity_8: 'Kostenfreies WLAN',
                amenity_9: 'Kostenfreier Parkplatz',
                amenity_10: 'Klimaanlage',
                amenity_11: 'Garten & Terrasse',
                amenity_12: 'Kamin',
                amenity_13: 'E-Ladestelle',
                amenity_14: 'Haustierfreundlich',
                amenity_15: '24/7 Anmeldung',
                amenity_16: 'Gartenblick',
                amenity_17: 'Bügeleisen und Bügelbrett',
                location_title: 'Standort & Sehenswürdigkeiten in der Nähe',
                location_intro: 'Entdecken Sie den mittelalterlichen Charme von Kőszeg und erkunden Sie die wunderschöne österreichisch-ungarische Grenzregion',
                attractions_title: 'Sehenswürdigkeiten in der Nähe',
                attr_0: 'Burg Jurisics',
                attr_1: 'Historische Altstadt Kőszeg',
                attr_2: 'Írottkő Naturschutzgebiet',
                attr_3: 'Siebenbrunnen (Hétforrás)',
                attr_4: 'Burg Lockenhaus (12 km)',
                attr_5: 'Sofersee (18 km)',
                gallery_title: 'Fotogalerie',
                booking_title: 'Buchen Sie Ihren Aufenthalt',
                form_checkin: 'Anreisedatum',
                form_checkout: 'Abreisedatum',
                form_adults: 'Anzahl der Erwachsenen',
                form_children: 'Anzahl der Kinder',
                form_select: 'Wählen...',
                form_submit: 'Verfügbarkeit prüfen',
                checkin_title: 'Check-in & Check-out Zeiten',
                checkin_label: 'Check-in:',
                checkout_label: 'Check-out:',
                footer_contact: 'Kontaktinformationen',
                footer_links: 'Schnelllinks',
                footer_copyright: '© 2025 Tessa Central House. Alle Rechte vorbehalten.'
            }
        };

        let currentLanguage = 'hu';

        function changeLanguage(lang) {
            currentLanguage = lang;
            document.getElementById('currentLang').textContent = lang.toUpperCase();
            
            // Update all elements with data-lang attribute
            document.querySelectorAll('[data-lang]').forEach(element => {
                const key = element.getAttribute('data-lang');
                if (translations[lang] && translations[lang][key]) {
                    element.textContent = translations[lang][key];
                }
            });

            // Update gallery items with data-lang-label
            document.querySelectorAll('[data-lang-label]').forEach(element => {
                const key = element.getAttribute('data-lang-label');
                if (translations[lang] && translations[lang][key]) {
                    element.textContent = translations[lang][key];
                }
            });
        }